/**
 * Minimal internal i18n for UI chrome only (no library).
 *
 * Scope: buttons, labels, headings, helper text, empty states, navigation,
 * static status copy. It deliberately does NOT cover the live transcript, user
 * speech, AI tutor replies, or grading/analysis bodies generated by the backend
 * — LUVE stays an English speaking-practice app, so practice content remains in
 * its original language.
 *
 * `en` is the source of truth for the key set; `vi` is typed to it, so a missing
 * Vietnamese key is a compile error. `translate` falls back to English, then to
 * the raw key, and supports simple `{name}` placeholder substitution.
 */
export type UiLanguage = "en" | "vi";

const en = {
  // Top bar / navigation
  "nav.ready": "Ready",
  "nav.signOut": "Sign out",
  "nav.pastSessions": "Past sessions",
  "nav.diagnostics": "Developer diagnostics",
  "lang.switchAria": "Switch interface language",

  // Intro / landing
  "intro.eyebrow": "Speaking practice, with an AI coach",
  "intro.h1a": "Practice speaking English, out loud,",
  "intro.h1em": "without the nerves.",
  "intro.lead":
    "Have a real spoken conversation with an AI tutor. When you're done, get calm, specific coaching on your fluency, grammar and vocabulary.",
  "intro.start": "Start practicing",
  "intro.haveAccount": "I already have an account",
  "intro.note": "A focused demo build — one practice session at a time.",
  "intro.how": "How a session works",
  "intro.step1": "Speak naturally",
  "intro.step1d": "Your mic streams to the tutor in real time.",
  "intro.step2": "Listen & respond",
  "intro.step2d": "The tutor replies out loud — a real back-and-forth.",
  "intro.step3": "Get coaching",
  "intro.step3d": "End the session for scores and specific corrections.",

  // Auth
  "auth.back": "Back",
  "auth.signIn": "Sign in",
  "auth.createAccount": "Create account",
  "auth.username": "Username",
  "auth.usernamePh": "At least 3 characters",
  "auth.email": "Email",
  "auth.password": "Password",
  "auth.passwordPh": "At least 8 characters",
  "auth.signingIn": "Signing in…",
  "auth.creatingAccount": "Creating account…",
  "auth.or": "or",
  "auth.google": "Continue with Google",
  "auth.googleNote": "Google sign-in isn't set up on this build yet — use your email and password.",
  "auth.errEmail": "Enter your email address.",
  "auth.errPwd": "Password must be at least 8 characters.",
  "auth.errUname": "Choose a username with at least 3 characters.",
  "auth.errGeneric": "Something went wrong. Try again.",

  // Home (authenticated)
  "home.welcome": "Welcome back, {name}",
  "home.h2": "Ready for a conversation?",
  "home.lead": "Find a quiet spot, allow your microphone, and start talking. The tutor will respond out loud.",
  "home.start": "Start practice",
  "home.starting": "Starting…",
  "home.settings": "Practice settings",
  "home.oneSession": "One session at a time",
  "home.transcriptOnly": "Transcript only",
  "home.transcriptOnlyDesc": "Practice without the tutor's voice (STT only).",
  "home.muteTutor": "Mute tutor audio",
  "home.muteTutorDesc": "See replies as text, no spoken audio.",

  // Live conversation
  "live.session": "Practice session",
  "live.end": "End session",
  "live.authWarn": "Your sign-in session is ending soon. End now to save and grade this practice.",
  "live.endGradeNow": "End and grade now",
  "live.micMuted": "Microphone muted",
  "live.langNote":
    "LUVE focuses on English speaking practice. Please speak English; Vietnamese or other languages may be misrecognized as English.",
  "live.transcript": "Transcript",
  "live.emptyTranscript": "Your conversation will appear here as you speak…",
  "live.you": "You",
  "live.mute": "Mute",
  "live.unmute": "Unmute",
  "live.kbdHint": "Tip: press Space to mute or unmute the mic.",

  // Live phase states (status label / helper / connection chip)
  "phase.connecting.label": "Connecting…",
  "phase.connecting.help": "Setting up your session",
  "phase.connecting.chip": "Connecting",
  "phase.listening.label": "Listening…",
  "phase.listening.help": "Speak naturally — I'm listening",
  "phase.listening.chip": "Connected",
  "phase.speaking.label": "You're speaking",
  "phase.speaking.help": "Keep going — I'm following along",
  "phase.speaking.chip": "Connected",
  "phase.stt.label": "Got it…",
  "phase.stt.help": "Finishing what you said",
  "phase.stt.chip": "Processing",
  "phase.thinking.label": "Thinking…",
  "phase.thinking.help": "Your tutor is forming a reply",
  "phase.thinking.chip": "Thinking",
  "phase.aispeaking.label": "Your tutor is speaking",
  "phase.aispeaking.help": "Your tutor is replying — listen along",
  "phase.aispeaking.chip": "Connected",

  // Ended
  "ended.h2": "Nice work.",
  "ended.body": "We're reviewing your conversation…",

  // Recent sessions (history panel)
  "history.title": "Your sessions",
  "history.countLoaded": "{n} of {total} practice sessions",
  "history.countEmpty": "No practice sessions yet",
  "history.countError": "History unavailable",
  "history.countLoading": "Loading practice sessions",
  "history.emptyTitle": "No sessions yet.",
  "history.emptyBody": "Start a practice session and it will appear here when the backend stores it.",
  "history.retry": "Retry",
  "history.current": "Current",
  "history.foot": "Select a session to open its saved summary and grading status. Transcript replay is coming later.",
  "history.ariaPanel": "Your past sessions",
  "history.ariaClose": "Close history",
  "history.tokens": "{n} tokens",
  "history.manualStops": "{n} manual stops",
  "history.ended": "Ended {time}",

  // Analysis
  "analysis.titleSaved": "Saved session analysis",
  "analysis.titleYours": "Your session analysis",
  "analysis.titleSummary": "Session summary",
  "analysis.chipLoading": "Loading grading…",
  "analysis.chipHistory": "History",
  "analysis.chipPreview": "Preview",
  "analysis.chipGraded": "Graded",
  "analysis.loadingHint": "This usually takes a few seconds.",
  "analysis.pendingRunning": "Grading is running",
  "analysis.pendingQueued": "Grading pending",
  "analysis.pendingBody":
    "This session has ended and LUVE is waiting for the grading worker to finish. No score is shown until the real grading result is available.",
  "analysis.detectedWords": "Detected student words",
  "analysis.checkAgain": "Check again",
  "analysis.pastSessions": "Past sessions",
  "analysis.insufficientTitle": "Not enough for full grading yet",
  "analysis.insufficientBody":
    "We caught some speech, but not enough reliable English for a full score. Short phrases are still useful practice; try one longer answer so LUVE can give real feedback.",
  "analysis.reason": "Reason",
  "analysis.tryLonger": "Try one longer answer",
  "analysis.failedTitle": "Grading failed",
  "analysis.unavailableTitle": "Grading unavailable",
  "analysis.unavailableBody": "LUVE couldn't load a grading result for this session yet.",
  "analysis.retry": "Retry",
  "analysis.practiceAgain": "Practice again",
  "analysis.historyBannerTitle": "Checking saved-session grading",
  "analysis.historyBannerBody":
    "this view starts from the real saved session summary, then loads any real grading status or result for the selected session. Transcript replay is still deferred.",
  "analysis.availableNow": "Available now",
  "analysis.availableNowBody":
    "LUVE can show the saved session summary now and will load real grading status or result from the authenticated grading endpoint when it is available.",
  "analysis.deferred": "Deferred",
  "analysis.deferredBody": "Transcript replay is still deferred because the history list intentionally stays lean.",
  "analysis.sessionDetails": "Session details",
  "analysis.selectedPast": "Selected past session",
  "analysis.previewTitle": "Preview feedback",
  "analysis.previewBody":
    "automatically generated for the demo, not final pedagogical grading. This warning comes from the grading API.",
  "analysis.scoreOverall": "Overall",
  "analysis.scoreFluency": "Fluency",
  "analysis.scoreGrammar": "Grammar",
  "analysis.scoreVocab": "Vocabulary",
  "analysis.scorePronunciation": "Pronunciation",
  "analysis.coachSummary": "Coach's summary",
  "analysis.noSummary": "The grader returned no written summary.",
  "analysis.corrections": "Corrections",
  "analysis.noCorrections": "No specific corrections were returned.",
  "analysis.skillFeedback": "Skill feedback",
  "analysis.metricStarted": "Started",
  "analysis.metricEnded": "Ended",
  "analysis.metricTokens": "Tokens",
  "analysis.metricStops": "Stops",
  "analysis.metricManualStops": "Manual stops",
} as const;

export type TKey = keyof typeof en;
export type TParams = Record<string, string | number>;

const vi: Record<TKey, string> = {
  // Top bar / navigation
  "nav.ready": "Sẵn sàng",
  "nav.signOut": "Đăng xuất",
  "nav.pastSessions": "Lịch sử luyện tập",
  "nav.diagnostics": "Công cụ chẩn đoán",
  "lang.switchAria": "Đổi ngôn ngữ giao diện",

  // Intro / landing
  "intro.eyebrow": "Luyện nói cùng gia sư AI",
  "intro.h1a": "Luyện nói tiếng Anh thành tiếng,",
  "intro.h1em": "không còn lo lắng.",
  "intro.lead":
    "Trò chuyện thực sự bằng giọng nói với gia sư AI. Khi xong, bạn nhận được nhận xét nhẹ nhàng, cụ thể về độ trôi chảy, ngữ pháp và từ vựng.",
  "intro.start": "Bắt đầu luyện tập",
  "intro.haveAccount": "Tôi đã có tài khoản",
  "intro.note": "Bản demo tập trung — mỗi lần một phiên luyện tập.",
  "intro.how": "Một phiên luyện tập diễn ra thế nào",
  "intro.step1": "Nói tự nhiên",
  "intro.step1d": "Mic của bạn truyền tới gia sư theo thời gian thực.",
  "intro.step2": "Lắng nghe & trả lời",
  "intro.step2d": "Gia sư trả lời thành tiếng — một cuộc trò chuyện thật sự.",
  "intro.step3": "Nhận nhận xét",
  "intro.step3d": "Kết thúc phiên để xem điểm và các chỉnh sửa cụ thể.",

  // Auth
  "auth.back": "Quay lại",
  "auth.signIn": "Đăng nhập",
  "auth.createAccount": "Tạo tài khoản",
  "auth.username": "Tên người dùng",
  "auth.usernamePh": "Ít nhất 3 ký tự",
  "auth.email": "Email",
  "auth.password": "Mật khẩu",
  "auth.passwordPh": "Ít nhất 8 ký tự",
  "auth.signingIn": "Đang đăng nhập…",
  "auth.creatingAccount": "Đang tạo tài khoản…",
  "auth.or": "hoặc",
  "auth.google": "Tiếp tục với Google",
  "auth.googleNote": "Đăng nhập Google chưa được thiết lập ở bản này — hãy dùng email và mật khẩu.",
  "auth.errEmail": "Vui lòng nhập email.",
  "auth.errPwd": "Mật khẩu phải có ít nhất 8 ký tự.",
  "auth.errUname": "Chọn tên người dùng có ít nhất 3 ký tự.",
  "auth.errGeneric": "Có lỗi xảy ra. Vui lòng thử lại.",

  // Home (authenticated)
  "home.welcome": "Chào mừng trở lại, {name}",
  "home.h2": "Sẵn sàng trò chuyện chưa?",
  "home.lead": "Tìm một nơi yên tĩnh, cho phép dùng micro, và bắt đầu nói. Gia sư sẽ trả lời thành tiếng.",
  "home.start": "Bắt đầu luyện nói",
  "home.starting": "Đang bắt đầu…",
  "home.settings": "Cài đặt luyện tập",
  "home.oneSession": "Mỗi lần một phiên",
  "home.transcriptOnly": "Chỉ phụ đề",
  "home.transcriptOnlyDesc": "Luyện tập không có giọng gia sư (chỉ nhận dạng giọng nói).",
  "home.muteTutor": "Tắt tiếng gia sư",
  "home.muteTutorDesc": "Xem câu trả lời dạng văn bản, không phát tiếng.",

  // Live conversation
  "live.session": "Phiên luyện tập",
  "live.end": "Kết thúc",
  "live.authWarn": "Phiên đăng nhập của bạn sắp hết hạn. Hãy kết thúc ngay để lưu và chấm điểm phiên này.",
  "live.endGradeNow": "Kết thúc và chấm ngay",
  "live.micMuted": "Đã tắt mic",
  "live.langNote":
    "LUVE tập trung luyện nói tiếng Anh. Vui lòng nói tiếng Anh; tiếng Việt hoặc ngôn ngữ khác có thể bị nhận dạng sai thành tiếng Anh.",
  "live.transcript": "Phụ đề",
  "live.emptyTranscript": "Cuộc trò chuyện của bạn sẽ hiện ở đây khi bạn nói…",
  "live.you": "Bạn",
  "live.mute": "Tắt mic",
  "live.unmute": "Bật mic",
  "live.kbdHint": "Mẹo: nhấn Space để bật/tắt mic.",

  // Live phase states
  "phase.connecting.label": "Đang kết nối…",
  "phase.connecting.help": "Đang thiết lập phiên của bạn",
  "phase.connecting.chip": "Đang kết nối",
  "phase.listening.label": "Đang nghe…",
  "phase.listening.help": "Cứ nói tự nhiên — tôi đang nghe",
  "phase.listening.chip": "Đã kết nối",
  "phase.speaking.label": "Bạn đang nói",
  "phase.speaking.help": "Cứ tiếp tục — tôi đang theo dõi",
  "phase.speaking.chip": "Đã kết nối",
  "phase.stt.label": "Đã nhận…",
  "phase.stt.help": "Đang hoàn tất câu của bạn",
  "phase.stt.chip": "Đang xử lý",
  "phase.thinking.label": "Đang suy nghĩ…",
  "phase.thinking.help": "Gia sư đang soạn câu trả lời",
  "phase.thinking.chip": "Đang suy nghĩ",
  "phase.aispeaking.label": "Gia sư đang nói",
  "phase.aispeaking.help": "Gia sư đang trả lời — hãy lắng nghe",
  "phase.aispeaking.chip": "Đã kết nối",

  // Ended
  "ended.h2": "Làm tốt lắm.",
  "ended.body": "Đang xem lại cuộc trò chuyện của bạn…",

  // Recent sessions (history panel)
  "history.title": "Lịch sử luyện tập",
  "history.countLoaded": "{n}/{total} phiên luyện tập",
  "history.countEmpty": "Chưa có phiên luyện tập nào",
  "history.countError": "Không tải được lịch sử",
  "history.countLoading": "Đang tải các phiên luyện tập",
  "history.emptyTitle": "Chưa có phiên nào.",
  "history.emptyBody": "Bắt đầu một phiên luyện tập và nó sẽ hiện ở đây khi được lưu lại.",
  "history.retry": "Thử lại",
  "history.current": "Hiện tại",
  "history.foot": "Chọn một phiên để mở tóm tắt đã lưu và trạng thái chấm điểm. Tính năng xem lại phụ đề sẽ có sau.",
  "history.ariaPanel": "Các phiên đã qua",
  "history.ariaClose": "Đóng lịch sử",
  "history.tokens": "{n} token",
  "history.manualStops": "{n} lần dừng thủ công",
  "history.ended": "Kết thúc {time}",

  // Analysis
  "analysis.titleSaved": "Phân tích phiên đã lưu",
  "analysis.titleYours": "Phân tích phiên của bạn",
  "analysis.titleSummary": "Tóm tắt phiên",
  "analysis.chipLoading": "Đang tải chấm điểm…",
  "analysis.chipHistory": "Lịch sử",
  "analysis.chipPreview": "Bản xem trước",
  "analysis.chipGraded": "Đã chấm",
  "analysis.loadingHint": "Thường mất vài giây.",
  "analysis.pendingRunning": "Đang chấm điểm",
  "analysis.pendingQueued": "Đang chờ chấm điểm",
  "analysis.pendingBody":
    "Phiên này đã kết thúc và LUVE đang chờ bộ chấm điểm hoàn tất. Chưa hiển thị điểm cho tới khi có kết quả chấm thật.",
  "analysis.detectedWords": "Số từ học viên nhận được",
  "analysis.checkAgain": "Kiểm tra lại",
  "analysis.pastSessions": "Lịch sử luyện tập",
  "analysis.insufficientTitle": "Chưa đủ dữ liệu để chấm đầy đủ",
  "analysis.insufficientBody":
    "Chúng tôi đã nghe được một ít, nhưng chưa đủ tiếng Anh đáng tin để chấm đầy đủ. Câu ngắn vẫn hữu ích; hãy thử một câu trả lời dài hơn để LUVE đưa nhận xét thật.",
  "analysis.reason": "Lý do",
  "analysis.tryLonger": "Thử một câu dài hơn",
  "analysis.failedTitle": "Chấm điểm thất bại",
  "analysis.unavailableTitle": "Chưa có kết quả chấm",
  "analysis.unavailableBody": "LUVE chưa tải được kết quả chấm cho phiên này.",
  "analysis.retry": "Thử lại",
  "analysis.practiceAgain": "Luyện lại",
  "analysis.historyBannerTitle": "Đang kiểm tra chấm điểm phiên đã lưu",
  "analysis.historyBannerBody":
    "màn hình này bắt đầu từ tóm tắt phiên đã lưu thật, sau đó tải trạng thái hoặc kết quả chấm thật cho phiên được chọn. Xem lại phụ đề vẫn chưa khả dụng.",
  "analysis.availableNow": "Có sẵn ngay",
  "analysis.availableNowBody":
    "LUVE có thể hiển thị tóm tắt phiên đã lưu ngay và sẽ tải trạng thái hoặc kết quả chấm thật từ API chấm điểm khi có.",
  "analysis.deferred": "Tạm hoãn",
  "analysis.deferredBody": "Xem lại phụ đề vẫn tạm hoãn vì danh sách lịch sử cố ý giữ gọn nhẹ.",
  "analysis.sessionDetails": "Chi tiết phiên",
  "analysis.selectedPast": "Phiên đã chọn trước đó",
  "analysis.previewTitle": "Nhận xét xem trước",
  "analysis.previewBody":
    "được tạo tự động cho bản demo, không phải chấm điểm sư phạm cuối cùng. Cảnh báo này đến từ API chấm điểm.",
  "analysis.scoreOverall": "Tổng quát",
  "analysis.scoreFluency": "Độ trôi chảy",
  "analysis.scoreGrammar": "Ngữ pháp",
  "analysis.scoreVocab": "Từ vựng",
  "analysis.scorePronunciation": "Phát âm",
  "analysis.coachSummary": "Tóm tắt của gia sư",
  "analysis.noSummary": "Bộ chấm điểm không trả về tóm tắt nào.",
  "analysis.corrections": "Chỉnh sửa",
  "analysis.noCorrections": "Không có chỉnh sửa cụ thể nào.",
  "analysis.skillFeedback": "Nhận xét kỹ năng",
  "analysis.metricStarted": "Bắt đầu",
  "analysis.metricEnded": "Kết thúc",
  "analysis.metricTokens": "Token",
  "analysis.metricStops": "Lần dừng",
  "analysis.metricManualStops": "Lần dừng thủ công",
};

export const DICT: Record<UiLanguage, Record<TKey, string>> = { en, vi };

export function translate(lang: UiLanguage, key: TKey, params?: TParams): string {
  const template = DICT[lang][key] ?? DICT.en[key] ?? key;
  if (!params) return template;
  return Object.keys(params).reduce(
    (acc, name) => acc.replace(new RegExp(`\\{${name}\\}`, "g"), String(params[name])),
    template,
  );
}
